apiVersion: v1
kind: Service
metadata:
  name: sdapi
  labels:
    app: screwdriver
    tier: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: screwdriver
    tier: api
